// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_headerPanel;
extern lv_obj_t * ui_deviceNameLabel;
extern lv_obj_t * ui_wifiImage;
extern lv_obj_t * ui_timedateBGPanel;
extern lv_obj_t * ui_GMTLabel;
extern lv_obj_t * ui_GMT;
extern lv_obj_t * ui_DSTLabel;
extern lv_obj_t * ui_DST;
extern lv_obj_t * ui_timeH;
extern lv_obj_t * ui_timeColon;
extern lv_obj_t * ui_timeM;
extern lv_obj_t * ui_timeS;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_brightnessImage;
extern lv_obj_t * ui_brightnessBar;
extern lv_obj_t * ui_maxBrightnessLabel;
extern lv_obj_t * ui_minBrightnessLabel;
extern lv_obj_t * ui_footerPanel;
extern lv_obj_t * ui_RSSILabel;
extern lv_obj_t * ui_RSSI;
extern lv_obj_t * ui_IPaddLabel;
extern lv_obj_t * ui_IPadd;
extern lv_obj_t * ui_rtcSyncedLabel;
extern lv_obj_t * ui_rtcSynced;
extern lv_obj_t * ui_rtcFailed;
extern lv_obj_t * ui_lastSyncTimeLabel;
extern lv_obj_t * ui_lastSyncTime;
extern lv_obj_t * ui_FPSLabel;
extern lv_obj_t * ui_FPS;
extern lv_obj_t * ui_CPUtempLabel;
extern lv_obj_t * ui_CPUtemp;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_640501820);    // assets/SiemensTIA-Background-320x170.png
LV_IMG_DECLARE(ui_img_472354705);    // assets/wifi-24px.png
LV_IMG_DECLARE(ui_img_901948647);    // assets/brightness-adjust-24px.png

// FONTS
LV_FONT_DECLARE(ui_font_14segment10);
LV_FONT_DECLARE(ui_font_14segment18);
LV_FONT_DECLARE(ui_font_7segment18);
LV_FONT_DECLARE(ui_font_7segment36);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
