// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t * ui_mainScreen;
lv_obj_t * ui_headerPanel;
lv_obj_t * ui_deviceNameLabel;
lv_obj_t * ui_wifiImage;
lv_obj_t * ui_timedateBGPanel;
lv_obj_t * ui_GMTLabel;
lv_obj_t * ui_GMT;
lv_obj_t * ui_DSTLabel;
lv_obj_t * ui_DST;
lv_obj_t * ui_timeH;
lv_obj_t * ui_timeColon;
lv_obj_t * ui_timeM;
lv_obj_t * ui_timeS;
lv_obj_t * ui_day;
lv_obj_t * ui_date;
lv_obj_t * ui_brightnessImage;
lv_obj_t * ui_brightnessBar;
lv_obj_t * ui_maxBrightnessLabel;
lv_obj_t * ui_minBrightnessLabel;
lv_obj_t * ui_footerPanel;
lv_obj_t * ui_RSSILabel;
lv_obj_t * ui_RSSI;
lv_obj_t * ui_IPaddLabel;
lv_obj_t * ui_IPadd;
lv_obj_t * ui_rtcSyncedLabel;
lv_obj_t * ui_rtcSynced;
lv_obj_t * ui_rtcFailed;
lv_obj_t * ui_lastSyncTimeLabel;
lv_obj_t * ui_lastSyncTime;
lv_obj_t * ui_FPSLabel;
lv_obj_t * ui_FPS;
lv_obj_t * ui_CPUtempLabel;
lv_obj_t * ui_CPUtemp;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainScreen);
}
