// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_img_src(ui_mainScreen, &ui_img_640501820, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_mainScreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_headerPanel, 320);
    lv_obj_set_height(ui_headerPanel, 30);
    lv_obj_set_x(ui_headerPanel, 0);
    lv_obj_set_y(ui_headerPanel, -70);
    lv_obj_set_align(ui_headerPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_headerPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_headerPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_headerPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_headerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_headerPanel, lv_color_hex(0x232121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_headerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_headerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_headerPanel, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deviceNameLabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_deviceNameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deviceNameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deviceNameLabel, -32);
    lv_obj_set_y(ui_deviceNameLabel, -72);
    lv_obj_set_align(ui_deviceNameLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_deviceNameLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_deviceNameLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_deviceNameLabel, "LillyGo T-Display-S3 - ESP32Time Clock");
    lv_obj_clear_flag(ui_deviceNameLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_deviceNameLabel, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_deviceNameLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_deviceNameLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_deviceNameLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiImage = lv_img_create(ui_mainScreen);
    lv_img_set_src(ui_wifiImage, &ui_img_472354705);
    lv_obj_set_width(ui_wifiImage, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_wifiImage, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_wifiImage, 145);
    lv_obj_set_y(ui_wifiImage, -70);
    lv_obj_set_align(ui_wifiImage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_wifiImage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wifiImage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_wifiImage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_zoom(ui_wifiImage, 225);
    lv_obj_set_style_opa(ui_wifiImage, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_wifiImage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_wifiImage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timedateBGPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_timedateBGPanel, 222);
    lv_obj_set_height(ui_timedateBGPanel, 90);
    lv_obj_set_x(ui_timedateBGPanel, -10);
    lv_obj_set_y(ui_timedateBGPanel, 0);
    lv_obj_set_align(ui_timedateBGPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_timedateBGPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_timedateBGPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_timedateBGPanel,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_timedateBGPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_timedateBGPanel, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timedateBGPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_timedateBGPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_timedateBGPanel, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GMTLabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_GMTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GMTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GMTLabel, -252);
    lv_obj_set_y(ui_GMTLabel, -38);
    lv_obj_set_align(ui_GMTLabel, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_GMTLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_GMTLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_GMTLabel, "GMT:");
    lv_obj_set_style_text_color(ui_GMTLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GMTLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GMTLabel, &ui_font_14segment10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GMT = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_GMT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GMT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GMT, 70);
    lv_obj_set_y(ui_GMT, -38);
    lv_obj_set_align(ui_GMT, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_GMT, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_GMT, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_GMT, "+2");
    lv_obj_set_style_text_color(ui_GMT, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GMT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GMT, &ui_font_14segment10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DSTLabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_DSTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DSTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DSTLabel, 59);
    lv_obj_set_y(ui_DSTLabel, -38);
    lv_obj_set_align(ui_DSTLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DSTLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DSTLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_DSTLabel, "DST:");
    lv_obj_clear_flag(ui_DSTLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_DSTLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DSTLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DSTLabel, &ui_font_14segment10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DST = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_DST, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DST, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DST, -61);
    lv_obj_set_y(ui_DST, -38);
    lv_obj_set_align(ui_DST, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_DST, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DST, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_DST, "OFF");
    lv_obj_clear_flag(ui_DST, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_DST, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DST, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DST, &ui_font_14segment10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeH = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_timeH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeH, -189);
    lv_obj_set_y(ui_timeH, -10);
    lv_obj_set_align(ui_timeH, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_timeH, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_timeH, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_timeH, "00");
    lv_obj_set_style_text_color(ui_timeH, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeH, &ui_font_7segment36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeColon = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_timeColon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeColon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeColon, -25);
    lv_obj_set_y(ui_timeColon, -10);
    lv_obj_set_align(ui_timeColon, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_timeColon, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_timeColon, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_timeColon, ":");
    lv_obj_set_style_text_color(ui_timeColon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeColon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeColon, &ui_font_7segment36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeM = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_timeM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeM, -124);
    lv_obj_set_y(ui_timeM, -10);
    lv_obj_set_align(ui_timeM, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_timeM, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_timeM, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_timeM, "00");
    lv_obj_set_style_text_color(ui_timeM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeM, &ui_font_7segment36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeS = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_timeS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeS, -92);
    lv_obj_set_y(ui_timeS, -1);
    lv_obj_set_align(ui_timeS, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_timeS, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_timeS, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_timeS, "00");
    lv_obj_set_style_text_color(ui_timeS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeS, &ui_font_7segment18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day, -227);
    lv_obj_set_y(ui_day, 25);
    lv_obj_set_align(ui_day, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_day, "DAY.");
    lv_obj_set_style_text_color(ui_day, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day, &ui_font_14segment18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, -68);
    lv_obj_set_y(ui_date, 25);
    lv_obj_set_align(ui_date, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_date, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_date, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_date, "DD-MM-YYYY");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &ui_font_7segment18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brightnessImage = lv_img_create(ui_mainScreen);
    lv_img_set_src(ui_brightnessImage, &ui_img_901948647);
    lv_obj_set_width(ui_brightnessImage, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_brightnessImage, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_brightnessImage, 138);
    lv_obj_set_y(ui_brightnessImage, 0);
    lv_obj_set_align(ui_brightnessImage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_brightnessImage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_brightnessImage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_brightnessImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_brightnessImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_brightnessImage, 224);

    ui_brightnessBar = lv_bar_create(ui_mainScreen);
    lv_bar_set_range(ui_brightnessBar, 80, 240);
    lv_bar_set_value(ui_brightnessBar, 160, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_brightnessBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_brightnessBar, 6);
    lv_obj_set_height(ui_brightnessBar, 103);
    lv_obj_set_x(ui_brightnessBar, 154);
    lv_obj_set_y(ui_brightnessBar, 0);
    lv_obj_set_align(ui_brightnessBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_brightnessBar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_outline_color(ui_brightnessBar, lv_color_hex(0x151515), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_brightnessBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_brightnessBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_brightnessBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_brightnessBar, lv_color_hex(0x797979), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightnessBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_brightnessBar, 160, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_maxBrightnessLabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_maxBrightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maxBrightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maxBrightnessLabel, 139);
    lv_obj_set_y(ui_maxBrightnessLabel, -47);
    lv_obj_set_align(ui_maxBrightnessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maxBrightnessLabel, "240");
    lv_obj_set_style_text_color(ui_maxBrightnessLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maxBrightnessLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maxBrightnessLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minBrightnessLabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_minBrightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minBrightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minBrightnessLabel, 142);
    lv_obj_set_y(ui_minBrightnessLabel, 47);
    lv_obj_set_align(ui_minBrightnessLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_minBrightnessLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_minBrightnessLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_minBrightnessLabel, "80");
    lv_obj_set_style_text_color(ui_minBrightnessLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minBrightnessLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minBrightnessLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_footerPanel = lv_obj_create(ui_mainScreen);
    lv_obj_set_width(ui_footerPanel, 320);
    lv_obj_set_height(ui_footerPanel, 30);
    lv_obj_set_x(ui_footerPanel, 0);
    lv_obj_set_y(ui_footerPanel, 70);
    lv_obj_set_align(ui_footerPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_footerPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_footerPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_footerPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_footerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_footerPanel, lv_color_hex(0x232121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_footerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_footerPanel, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSSILabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_RSSILabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSILabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSILabel, -145);
    lv_obj_set_y(ui_RSSILabel, 64);
    lv_obj_set_align(ui_RSSILabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RSSILabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RSSILabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_RSSILabel, "RSSI:");
    lv_obj_clear_flag(ui_RSSILabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_RSSILabel, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSILabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RSSILabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSILabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSSI = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_RSSI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RSSI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSSI, 32);
    lv_obj_set_y(ui_RSSI, 64);
    lv_obj_set_align(ui_RSSI, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_RSSI, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RSSI, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_RSSI, "-00 dBm");
    lv_obj_clear_flag(ui_RSSI, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_RSSI, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RSSI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RSSI, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSSI, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPaddLabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_IPaddLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPaddLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPaddLabel, -151);
    lv_obj_set_y(ui_IPaddLabel, 76);
    lv_obj_set_align(ui_IPaddLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_IPaddLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_IPaddLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_IPaddLabel, "IP:");
    lv_obj_clear_flag(ui_IPaddLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_IPaddLabel, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPaddLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPaddLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPaddLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPadd = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_IPadd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPadd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPadd, 31);
    lv_obj_set_y(ui_IPadd, 76);
    lv_obj_set_align(ui_IPadd, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_IPadd, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_IPadd, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_IPadd, "000.000.000.000");
    lv_obj_clear_flag(ui_IPadd, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_IPadd, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPadd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IPadd, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPadd, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rtcSyncedLabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_rtcSyncedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rtcSyncedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rtcSyncedLabel, 69);
    lv_obj_set_y(ui_rtcSyncedLabel, 64);
    lv_obj_set_align(ui_rtcSyncedLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rtcSyncedLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_rtcSyncedLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_rtcSyncedLabel, "ESP32T STATE:");
    lv_obj_clear_flag(ui_rtcSyncedLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_rtcSyncedLabel, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rtcSyncedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rtcSyncedLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rtcSyncedLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rtcSynced = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_rtcSynced, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rtcSynced, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rtcSynced, 134);
    lv_obj_set_y(ui_rtcSynced, 64);
    lv_obj_set_align(ui_rtcSynced, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rtcSynced, "SYNCED");
    lv_obj_clear_flag(ui_rtcSynced, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_rtcSynced, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rtcSynced, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rtcSynced, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_rtcSynced, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rtcFailed = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_rtcFailed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rtcFailed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rtcFailed, -4);
    lv_obj_set_y(ui_rtcFailed, 64);
    lv_obj_set_align(ui_rtcFailed, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_rtcFailed, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_rtcFailed, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_rtcFailed, "FAILED");
    lv_obj_clear_flag(ui_rtcFailed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_rtcFailed, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rtcFailed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rtcFailed, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_rtcFailed, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lastSyncTimeLabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lastSyncTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lastSyncTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lastSyncTimeLabel, -53);
    lv_obj_set_y(ui_lastSyncTimeLabel, 75);
    lv_obj_set_align(ui_lastSyncTimeLabel, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_lastSyncTimeLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_lastSyncTimeLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_lastSyncTimeLabel, "LAST SYNCED:");
    lv_obj_clear_flag(ui_lastSyncTimeLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lastSyncTimeLabel, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lastSyncTimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lastSyncTimeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lastSyncTime = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lastSyncTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lastSyncTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lastSyncTime, -4);
    lv_obj_set_y(ui_lastSyncTime, 76);
    lv_obj_set_align(ui_lastSyncTime, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_lastSyncTime, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_lastSyncTime, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_lastSyncTime, "00:00:00");
    lv_obj_clear_flag(ui_lastSyncTime, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lastSyncTime, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lastSyncTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lastSyncTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lastSyncTime, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FPSLabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_FPSLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FPSLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FPSLabel, -160);
    lv_obj_set_y(ui_FPSLabel, 76);
    lv_obj_set_align(ui_FPSLabel, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_FPSLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FPSLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_FPSLabel, "FPS:");
    lv_obj_set_style_text_color(ui_FPSLabel, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FPSLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FPSLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FPS = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_FPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FPS, -142);
    lv_obj_set_y(ui_FPS, 76);
    lv_obj_set_align(ui_FPS, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_FPS, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FPS, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_FPS, "00");
    lv_obj_set_style_text_color(ui_FPS, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FPS, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CPUtempLabel = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_CPUtempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CPUtempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CPUtempLabel, -25);
    lv_obj_set_y(ui_CPUtempLabel, 64);
    lv_obj_set_align(ui_CPUtempLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CPUtempLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CPUtempLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_CPUtempLabel, "CPU:");
    lv_obj_clear_flag(ui_CPUtempLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_CPUtempLabel, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CPUtempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CPUtempLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CPUtemp = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_CPUtemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CPUtemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CPUtemp, -143);
    lv_obj_set_y(ui_CPUtemp, 64);
    lv_obj_set_align(ui_CPUtemp, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_CPUtemp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CPUtemp, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_CPUtemp, "00 C");
    lv_obj_clear_flag(ui_CPUtemp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_CPUtemp, lv_color_hex(0xB5B5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CPUtemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CPUtemp, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}
